### ISSUE TITLE
PYFA 1.26.0: Mining Foreman Burst II boosts is incorrect

### ISSUE THREAD

**Issue by vmech** [pyfa-org/Pyfa#892]
Mining Director skill effect is lost:
http://image.prntscr.com/image/6506fbf544dd4db9b7c50aa108ad8903.png

Effects strength in PYFA:
http://image.prntscr.com/image/6c315b9bc766424ca76e2f2e129e414b.png

Effects strength in EVE:
http://image.prntscr.com/image/b181469c080e4c55a5ed141bbc6dcca6.png

**Comment by blitzmann** [comment]
Can you EFT format fits here (the booster and the boostee). Thanks

**Comment by vmech** [comment]
```
[Orca, [w] Booster Asc #1]

Damage Control II
Expanded Cargohold II

500MN Cold-Gas Enduring Microwarpdrive
Adaptive Invulnerability Field II
Pithum C-Type Thermal Dissipation Amplifier
EM Ward Field II
Drone Navigation Computer II

Mining Foreman Burst II, Mining Equipment Preservation Charge
Mining Foreman Burst II, Mining Laser Field Enhancement Charge
Mining Foreman Burst II, Mining Laser Optimization Charge
Small Tractor Beam II
Small Tractor Beam II
[Empty High slot]

Large Ancillary Current Router I
Large Hyperspatial Velocity Optimizer II
Large Anti-Kinetic Screen Reinforcer II


Hobgoblin II x5
Medium Shield Maintenance Bot I x5
Mining Drone II x5
```
```
[Hulk, [w] Hulk Asc #1]

Mining Laser Upgrade II
Mining Laser Upgrade II
Co-Processor II

Adaptive Invulnerability Field II
EM Ward Field II
Pithum C-Type Thermal Dissipation Amplifier
Survey Scanner II

Modulated Strip Miner II, Omber Mining Crystal II
Modulated Strip Miner II, Omber Mining Crystal II

Medium Anti-Kinetic Screen Reinforcer II
Medium Core Defense Field Extender II
```

**Comment by vmech** [comment]
What was fixed? I dont see any changes. All values remains incorrect:
http://image.prntscr.com/image/51c59a69f5f442048ef9be00ceba9248.png

Must be:
http://image.prntscr.com/image/4088377b07d441148129d9305cec7501.png

**Comment by Ebag333** [comment]
It's only fixed in the source.  If you're not running from the source, you won't see it it.

**Comment by vmech** [comment]
Can I get this fix? I very needed :(

**Comment by blitzmann** [comment]
This should be fixed in 1.26.0, released yesterday. Please double check your version, and let me know if it's still broken.

**Comment by vmech** [comment]
blitzmann, my last report from 1.26.0. Mining boosts still incorrect :(
http://image.prntscr.com/image/8605b7c6bb694bab8e79f1c7634558e4.png

**Comment by Ebag333** [comment]
What are your skills?

**Comment by Ebag333** [comment]
@blitzmann the amounts are swapped.
http://image.prntscr.com/image/b181469c080e4c55a5ed141bbc6dcca6.png

The survey module and strip miners `range` is being multiplied by 1.41 (so a boost of 40.4%, or close enough to it).  That should be a multiplier of .809 (or the 80.9%).

The strip miners are getting their `activation cost` and `activation time` multiplied by 0.79, which is closeish to the 80.9% bonus.

The numbers are off slightly because I don't have the foreman link loaded in Pyfa, and I'm too lazy to go back and fix it.

We don't seem to handle the mining crystal bonus at all.  I would _guess_ that would modify `crystalVolatilityDamage` but that's not something major.

I don't see anything obvious in the effect that'd cause them to be swapped.  But they most definitely are, compared to the in game screenshot.

**Comment by vmech** [comment]
Ebag333, for mining yield and mining boosts all 5.

**Comment by vmech** [comment]
Ok. Just simple explain.

**Mining Director:**
Increases the strength of Mining Foreman Burst effects by 10% per skill level.

**Mining Foreman Burst II:**
+25% bonus to the effect strength of Mining Foreman Burst charges launched from this module.

**Mining Foreman Mindlink:**
+25% bonus to Mining Foreman Burst effect strength and duration.

**Industrial Command Ships bonuses (per skill level):**
3% bonus to Mining Foreman Burst effect strength and duration.

For Mining Laser Field Enhancement Charge:
30% * (1 + (10 * 5)/100) * 1.25 * 1.25 * (1 + (3 * 5)/100) = 80,859375%

For Mining Laser Optimization Charge:
-15% * (1 + (10 * 5)/100) * 1.25 * 1.25 * (1 + (3 * 5)/100) = -40,4296875%

For Mining Equipment Preservation Charge:
-15% * (1 + (10 * 5)/100) * 1.25 * 1.25 * (1 + (3 * 5)/100) = -40,4296875%

**Comment by blitzmann** [comment]
Will take a look :)

**Comment by blitzmann** [comment]
@vmech sorry about the delay, this issue dropped off my radar...

For better understanding and to ensure that I'm working with the same skills you're working with can you send me your pyfa database file? It's located at `%userprofile%\.pyfa\saveddata.db`. Send that to sable.blitzmann@gmail.com And then just give me the name of the fits that the problem is happening on. I suspect this has to do with a stacking penalty not applying or soemthing, but I cannot reproduce the exact values you're getting. :)

**Comment by vmech** [comment]
1.26.1 preview still have same incorrect mining boosts.

**Comment by blitzmann** [comment]
Got this working

![image](https://cloud.githubusercontent.com/assets/3904767/23008539/478039c6-f3de-11e6-9296-44ce2eae7cb4.png)

It'll be available in v1.27.0 which should be out by this weekend. Sorry it took so long!

**Comment by vmech** [comment]
Hallelujah! \o/ :D
