### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by porowns** [pyfa-org/Pyfa#928]
Hey there, recently got this error and the solutions to previous instances of this error didn't resolve it. 
![d9ff6e7193d260ad845c5d06baa59b6b](https://cloud.githubusercontent.com/assets/16302735/21582402/dbfcf73a-d023-11e6-81b0-58cb6b40c1b1.png)

Tried reinstalling a few times to a few different locations, couldn't figure it out.

**Comment by blitzmann** [comment]
Did this just start recently? Was it working before? 

The actual issue is a case of database corruption. We don't know what causes it (hense the questions to gather more info), but we have a "fix" for it that should be coming in the next release. 

Could you send me a copy of your `%userprofile%/.pyfa/saveddata.db` file to the email in the README? I'll go ahead and fix it up and send it back to you. :)

**Comment by porowns** [comment]
Yeah, I installed Pyfa, originally tried to import a character with an EVEMON file, then wasn't able to interact at all with adding/duplicating/deleting characters. Could not create any new characters or anything.

After that, I renamed the All 5's to try and edit it, and this issue started occuring.

**Comment by Ebag333** [comment]
@blitzmann because EVEMon is out of date, I bet it has skills that we don't. So then the import fails, and poof corruption. 

A working theory at least, and something to look into...

**Comment by porowns** [comment]
@Ebag333 I no longer remember which specific character file I used, but I just imported them all and Pyfa seems to be working as intended. Must have been an odd outlier case. I can't seem to reproduce the issue.

**Comment by Ebag333** [comment]
>but I just imported them all and Pyfa seems to be working as intended.

Drat.

**Comment by porowns** [comment]
@Ebag333 Scratch that, just reproduced the issue, emailing you the file.

**Comment by Ebag333** [comment]
Anything special that you did to reproduce? Or just straight up import the file?

**Comment by porowns** [comment]
I did a clean installation of Pyfa, and imported that file as the first thing I did. The import did not work (no error message, just nothing happened), and after closing and reopening Pyfa, character editor is completely broken.

**Comment by blitzmann** [comment]
> I did a clean installation of Pyfa,

When you say clean installation, do you mean you nuked your user profile data as well?

Can you try to reproduce again? I know it's asking a lot, especially if you're trying to actually use the damn application, but if you can consistently reproduce, then this is the first time reproduction steps have been described that spawns that particular crash, which is pretty major as we can then drive down to hopefully find the root cause. Up until now it's been a phantom bug.

**Comment by Ebag333** [comment]
Well, unfortunately it doesn't recreate the issue as it imports fine for me. :(

I did find this though.
```
    <skill typeID="9999" name="Skill Doesn't Exist" level="1" skillpoints="1000" ownsBook="false" isKnown="true" />
    <skill typeID="9998" name="Skill Doesn't Exist" level="6" skillpoints="1000" ownsBook="false" isKnown="true" />
```

Obviously both these are invalid, but Pyfa happily imported them and injected them into the database.  So this is definitely a potential source of corruption.  I don't know if we want to go back and clean up old data, but we should catch typeIDs that aren't actually skills, and levels that don't fall in the 0-5 range.  That would prevent scenarios of importing a skill that no longer exists (super rare, I know, but might as well sanitize the import).

**Comment by porowns** [comment]
I cannot reproduce it a third time for some reason, it's an extremely weird error. Somehow, the character editor gets corrupted when importing an EVEMON file (sometimes), and after that the character editor completely breaks.

**Comment by Ebag333** [comment]
I don't think that the PR I just pushed fixes this if it's an intermittent issue.  But it would fix other potential issues, and changes the way errors are outputted.  Previously you wouldn't see them  at all, now critical exceptions are written to the log so if something goes terribly wrong, hopefully we'll at least see the exception.

**Comment by Ebag333** [comment]
>After that, I renamed the All 5's to try and edit it, and this issue started occuring.

This I can recreate.  For some reason when you first open the char window after importing, you can rename the All 5 char.  If you switch off it to another char and back on, that option goes away.

Not sure why it's being allowed in the first place....

**Comment by blitzmann** [comment]
@porowns, looking at the initial error more closely, it's very odd. It seems that it is trying to get the all 5 character, but can't find it, so it tries to create it... with an ID of 3 (all 5 is usually ID = 2). Which means there were two other characters there, which makes no sense.

>  I can still email you the DB file if you need it for error checking.

This would be helpful. sable.blitzmann@gmail.com

**Comment by blitzmann** [comment]
Actually... just re-read some other comments, and this makes much more sense:

> After that, I renamed the All 5's to try and edit it

This would be the problem. When we try to get the All 5 character, we do so by searching for it's name. Since you were able to rename the All 5 character, it couldn't find it, and thus tried to insert it again.

Still doesn't explain the integrity issue - it tries to create an all 5 character with ID of 3, but there's already id of 3 in the skills table. Would still like to see the database file if you could send it.

In the mean time, we've implemented a fix to bar users from re-naming the all 5 / 0 character. Additionally, we will be running database integrity check at startup to address the orphaned skill records (we still don't know where these are coming from, but this resolves the symptoms)

**Comment by porowns** [comment]
@blitzmann Sent you the file.

**Comment by blitzmann** [comment]
@porowns We have implemented something that should prevent this issue in the future. I'm hoping to have a new release out in the next couple days. :)
